# <https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html>
[licenses]
# List of explicitly allowed licenses. We are open to adding more! This is just the (almost) minimal list to satisfy
# current dependencies, but adding more is certainly an option.
#
# <https://spdx.org/licenses/>
allow = ["AGPL-3.0", "Apache-2.0", "BSD-3-Clause", "CDLA-Permissive-2.0", "ISC", "MIT", "MPL-2.0", "Unicode-3.0"]

# <https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html>
[advisories]
ignore = [
    # Advisory: `dtolnay/paste` is unmaintained. This is fine to ignore because it's not abandoned, it's just finished:
    #
    # > For my own use cases I would use paste since it is 'finished' and does everything I need.
    #
    # <https://github.com/rustsec/advisory-db/pull/2215#issuecomment-2709315704>
    "RUSTSEC-2024-0436",
]

# <https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html>
[bans]
# Don't warn about multiple versions of crates.
multiple-versions = "allow"

# <https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html>
[sources]
allow-git = [
    # Only temporary! `RemasteredArch/license_page` is tracking a PR branch from this repository instead of upstream
    # `cargo-license` because it replaces an unmaintained dependency (triggering warnings about `RUSTSEC-2021-0139`).
    #
    # Tracking issue: <https://github.com/RemasteredArch/license_page/issues/1>. Feel free to bother me
    # (@RemasteredArch) about removing this allow list entry if that issue closes (or if the PR lands and I haven't
    # started tracking upstream again).
    "https://github.com/Nitrokey/cargo-license",
    # This might or might not be temporary. This is my (@RemasteredArch) repository, so as a maintainer, there's an
    # assumed level of trust, but I might put `license_page` on crates.io too, we'll see.
    "https://github.com/RemasteredArch/license_page",
]
