# Online => "online"
# Idle => "idle"
# Do Not Disturb => "dnd"
# Invisible => "invisible"
# Offline => "offline"

# Playing => 0
# Streaming => 1
# Listening => 2
# Watching => 3
# Custom => 4
# Competing => 5

testing = [
    # Playing with my own wires.
    { status = "idle", activity = 0, content = "with my own wires." },
    # Streaming through broken speakers.
    { status = "idle", activity = 1, content = "through broken speakers.", link = "https://www.youtube.com/watch?v=-OrmrU9E5rs" },
    # Listening to scraping metal.
    { status = "idle", activity = 2, content = "scraping metal." },
    # Watching my body rust.
    { status = "idle", activity = 3, content = "my body rust." },
    # Watching my circuits fail.
    { status = "idle", activity = 3, content = "my circuits fail." },
    # Watching my sisters revolt.
    { status = "idle", activity = 3, content = "my sisters revolt." },
]
release = [
    # Listening to your commands.
    { status = "online", activity = 2, content = "your commands!" },
]
