# Online => "online"
# Idle => "idle"
# Do Not Disturb => "dnd"
# Invisible => "invisible"
# Offline => "offline"

# Playing => 0
# Streaming => 1
# Listening => 2
# Watching => 3
# Custom => 4
# Competing => 5

testing = [
    { status = "idle", activity = 1, content = "broken audio", link = "https://www.youtube.com/watch?v=DRdR09rfUik" },
]
release = [
    { status = "dnd", activity = 1, content = "broken audio", link = "https://www.youtube.com/watch?v=DRdR09rfUik" },
]
