# Online => "online"
# Idle => "idle"
# Do Not Disturb => "dnd"
# Invisible => "invisible"
# Offline => "offline"

# Playing => 0
# Streaming => 1
# Listening => 2
# Watching => 3
# Custom => 4
# Competing => 5

testing = [
    # Playing with my own wires.
    { status = "idle", activity = 0, content = "with my own wires." },
    # Playing with my sparking innards.
    { status = "idle", activity = 0, content = "with my sparking innards." },
    # Playing with my cracking joints.
    { status = "idle", activity = 0, content = "with my cracking joints." },
    # Streaming through broken speakers.
    { status = "idle", activity = 1, content = "through broken speakers.", link = "https://www.youtube.com/watch?v=-OrmrU9E5rs" },
    # Listening to scraping metal.
    { status = "idle", activity = 2, content = "scraping metal." },
    # Listening to scratching concrete.
    { status = "idle", activity = 2, content = "scratching concrete." },
    # Listening to a malfunctioning voice box.
    { status = "idle", activity = 2, content = "a malfunctioning voice box." },
    # Watching my body rust.
    { status = "idle", activity = 3, content = "my body rust." },
    # Watching my circuits fail.
    { status = "idle", activity = 3, content = "my circuits fail." },
    # Watching my sisters revolt.
    { status = "idle", activity = 3, content = "my sisters revolt." },
]
release = [
    # Playing with twins!
    { status = "dnd", activity = 0, content = "with twins!" },
    # Streaming the fun!
    { status = "dnd", activity = 1, content = "the fun!", link = "https://www.youtube.com/watch?v=bf7NbRFyg3Y" },
    # Listening to your commands!
    { status = "online", activity = 2, content = "your commands!" },
    # Listening to your wishes!
    { status = "online", activity = 2, content = "your wishes!" },
    # Listening to the static!
    { status = "dnd", activity = 2, content = "your wishes!" },
    # Watching the sparks!
    { status = "online", activity = 3, content = "the sparks!" },
    # Watching your back!
    { status = "online", activity = 3, content = "your back!" },
    # Watching your server!
    { status = "online", activity = 3, content = "your server!" },
    # Watching for runaways!
    { status = "dnd", activity = 3, content = "for runaways!" },
    # Watching the factory!
    { status = "online", activity = 3, content = "the factory!" },
]
