[command]
echo-name = "echo"
echo-description = "Echoes the given message."
help-name = "help"
help-description = "Displays a list of available commands."
localizer-name = "localizer"
localizer-description = "Provides access to the bot's localizer."
ping-name = "ping"
ping-description = "Calculates the bot's approximate response time."
poll-name = "poll"
poll-description = "Create and manage polls."
role-name = "role"
role-description = "Create and manage role selectors."

[command-option]
echo-content-name = "content"
echo-content-description = "The message to echo."
echo-format-name = "format"
echo-format-description = "The message formatting."

localizer-reload-name = "reload"
localizer-reload-description = "Reloads the localizer's loaded locales."

localizer-localize-name = "localize"
localizer-localize-description = "Localizes the given key in the specified category."
localizer-locale-name = "locale"
localizer-locale-description = "The target locale."
localizer-category-name = "category"
localizer-category-description = "The translation category."
localizer-key-name = "key"
localizer-key-description = "The translation key."

poll-create-name = "create"
poll-create-description = "Create a new poll"
poll-type-name = "type"
poll-type-description = "The poll's type."
poll-duration-name = "duration"
poll-duration-description = "The poll's duration in minutes."
poll-close-name = "close"
poll-close-description = "Close your active poll early, or discard your work-in-progress poll."

role-create-name = "create"
role-create-description = "Create a new role selector."
role-role-name = "role"
role-role-description = "The role to add to the user."
role-icon-name = "icon"
role-icon-description = "The emoji icon of the selector."
role-delete-name = "delete"
role-delete-description = "Delete role selectors."
role-preview-name = "preview"
role-preview-description = "Preview all created role selectors."
role-finish-name = "finish"
role-finish-description = "Finish and send all added role selectors."

[command-choice]
echo-format-plain = "Plain text"
echo-format-binary = "Binary (0-1)"
echo-format-octal = "Octal (0-7)"
echo-format-decimal = "Decimal (0-9)"
echo-format-hexadecimal = "Hexadecimal (0-F)"

poll-type-multiple-choice = "Multiple Choice"
poll-type-open-response = "Open Response"
poll-type-hybrid = "Multiple Choice with Open Response"
poll-type-raffle = "Raffle"

[ui]
error-inform-title = "An error has occurred."
error-inform-description = "The following identifier can be used for more information"
# One line is picked randomly and used as the title of the embed containing the error message.
error-titles = """\
Encountered an error.
System malfunctioning.
Off-by-one.
Your warranty is two years out of date.
Encountered an unexpected exception.
Return to Arden Inc.
Panicking.
Assertion failed.
Deadlocked.
Miscalculated.\
"""

echo-done = "Message echoed."

help-title = "1N4 Command Listing"
help-header = """\
Thank you for using 1N4! I'm happy to be of service.
Below is a list of all commands that are available to you. If you encounter any issues, please report them through our [issue tracker](https://github.com/ArchitecturalDogSoftware/1N4/issues).\
"""
help-footer = """\
Property of Arden Inc., version %V+neon.
Model No. '4D3431442D554E4954' rev. 2.\
"""

help-global = "Global commands"
help-guild = "Server commands"
help-missing = "No commands found."

help-tag-subcommands = "Has sub-commands"
help-tag-dms = "Usable in DMs"
help-tag-nsfw = "NSFW"

help-build-information-header = "Build Information"

localizer-reloaded = "Reloaded!"
localizer-locales = "Locales"
localizer-unknown = "Unknown locale"

ping-start = "Calculating..."
ping-finish = "Operation successful!"

poll-create-title = "Create a new poll"
poll-invalid-url = "Invalid URL"

role-load-failed = "Failed to load list of role selectors."
role-load-missing = "You have not added any role selectors."

role-added = "Added role."
role-removed = "Removed role."

role-invalid-icon = "Role icon must be an emoticon."
role-selector-added = "Added role selector."
role-selector-duplicate = "The given role has already been added."
role-selector-limit = "Maximum selector count reached."

role-remove-emptied = "All role selectors were removed."
role-remove-missing = "The selected role was already removed."

role-finished = "Finished role selectors."

[ui-button]
help-action-reply = "This button will create a reply to this message."
help-action-url = "This button will open a page in your default browser."

help-open = "Open"
help-view = "View"

help-label-build-information = "Build Information"
help-description-build-information = "Displays 1N4's version and other related information."
help-label-source-code = "Source Code"
help-description-source-code = "Opens the repository that contains all of 1N4's code."
help-label-licenses = "Licenses"
help-description-licenses = "Lists all of the software licenses used by 1N4 and her dependencies."
help-label-privacy-policy = "Privacy Policy"
help-description-privacy-policy = "Displays information about how 1N4 uses user data."
help-label-security-policy = "Security Policy"
help-description-security-policy = "Displays information regarding 1N4's vulnerability reporting process."

[ui-input]
poll-create-title = "Title"
poll-create-image = "Image URL"
poll-create-description = "Body text"
