[command]
echo-name = "eco"
echo-description = "Se hace eco del mensaje dado."
help-name = "ayuda"
help-description = "Muestra una lista de los comandos disponibles."
localizer-name = "traductor"
localizer-description = "Proporciona acceso al traductor del bot."
ping-name = "ping"
ping-description = "Calcula el tiempo de respuesta aproximado del bot."

[command-option]
echo-content-name = "contento"
echo-content-description = "El mensaje para resonar."
echo-format-name = "formato"
echo-format-description = "El formato del mensaje."

localizer-reload-name = "actualizar"
localizer-reload-description = "Actualiza las configuraciones regionales cargadas del traductor."

localizer-localize-name = "traducir"
localizer-localize-description = "Traduce la clave dada en la categoría especificada."
localizer-locale-name = "regional"
localizer-locale-description = "La configuración regional de destino."
localizer-category-name = "categoría"
localizer-category-description = "La categoría de traducción."
localizer-key-name = "clave"
localizer-key-description = "La clave de traducción."

[command-choice]
echo-format-plain = "Texto sin formato"
echo-format-binary = "Binario (0-1)"
echo-format-octal = "Octal (0-7)"
echo-format-decimal = "Decimal (0-9)"
echo-format-hexadecimal = "Hexadecimal (0-F)"

[ui]
echo-done = "Mensaje resonante."

help-title = "Listado de Comandos de 1N4"
help-header = """\
¡Gracias por usar 1N4! Estoy feliz de ser de servicio.
A continuación se muestra una lista de todos los comandos que están disponsibles para usted.

Si encuentra algún problema, por favor informalo a través de nuestro [rastreador de problemas](https://github.com/Jaxydog/1N4/issues).\
"""
help-footer = """\
Propiedad de Arden Inc., versión %V+neon.
Número de Modelo. '4D3431442D554E4954' cor. 2.\
"""

help-global = "Comandos globales"
help-guild = "Comandos del servidor"
help-missing = "No se han encontrado comandos."

help-tag-subcommands = "Tiene subcomandos"
help-tag-dms = "Utilizable en mensajes directos"
help-tag-nsfw = "NSFW"

localizer-reloaded = "¡Actualizado!"
localizer-locales = "Configuraciones regionales"
localizer-unknown = "Configuración regional desconocida"

ping-start = "Calculando..."
ping-finish = "Operación exitosa!"
