[command]
echo-name = "eco"
echo-description = "Se hace eco del mensaje dado."
help-name = "ayuda"
help-description = "Muestra una lista de los comandos disponibles."
localizer-name = "traductor"
localizer-description = "Proporciona acceso al traductor del bot."
ping-name = "ping"
ping-description = "Calcula el tiempo de respuesta aproximado del bot."
poll-name = "encuesta"
poll-description = "Crear y administrar encuestas."
role-name = "rol"
role-description = "Crear y administrar selectores de roles."

[command-option]
echo-content-name = "contento"
echo-content-description = "El mensaje para resonar."
echo-format-name = "formato"
echo-format-description = "El formato del mensaje."

localizer-reload-name = "actualizar"
localizer-reload-description = "Actualiza las configuraciones regionales cargadas del traductor."

localizer-localize-name = "traducir"
localizer-localize-description = "Traduce la clave dada en la categoría especificada."
localizer-locale-name = "regional"
localizer-locale-description = "La configuración regional de destino."
localizer-category-name = "categoría"
localizer-category-description = "La categoría de traducción."
localizer-key-name = "clave"
localizer-key-description = "La clave de traducción."

poll-create-name = "crear"
poll-create-description = "Crear una encuesta nueva."
poll-type-name = "tipo"
poll-type-description = "El tipo de la encuesta."
poll-duration-name = "minutos"
poll-duration-description = "La duración de la encuesta en minutos."
poll-close-name = "cerrar"
poll-close-description = "Cierre la encuesta activa antes de tiempo, o descarte la encuesta actual."

role-create-name = "crear"
role-create-description = "Crear un nuevo selector de roles."
role-role-name = "rol"
role-role-description = "El rol que se va a agregar al usario."
role-icon-name = "icono"
role-icon-description = "El icono de emoji del selector."
role-delete-name = "eliminar"
role-delete-description = "Eliminar selectores de roles."
role-preview-name = "vista_previa"
role-preview-description = "Vista previa de todos los selectores de roles creados."
role-finish-name = "finalizar"
role-finish-description = "Finalizar y enviar todos los selectores de roles agregados."

[command-choice]
echo-format-plain = "Texto sin formato"
echo-format-binary = "Binario (0-1)"
echo-format-octal = "Octal (0-7)"
echo-format-decimal = "Decimal (0-9)"
echo-format-hexadecimal = "Hexadecimal (0-F)"

poll-type-multiple-choice = "Opcíon múltiple"
poll-type-open-response = "Repuesta abierta"
poll-type-hybrid = "Opcíon múltiple y repuesta abierta"
poll-type-raffle = "Sorteo"

[ui]
error-inform-title = "Se ha producio un error."
error-inform-description = "El siguiente identificador se puede utilizar para obtener más información"
# Se selecciona aleatoriamente una línea y se usa como título del mensaje incrustado que contiene el mensaje del error.
error-titles = """\
Se encontró un error.
Mal functionamiento del sistema.
Apagado por uno.
Su garantía está desactualizada desde hace dos años.
Se encontró con una excepción inesperada.
Volver a Arden Inc.
Bloqueando.
Error de aserción.
Estanqué.
Calculé mal.\
"""

echo-done = "Mensaje resonante."

help-title = "Listado de Comandos de 1N4"
help-header = """\
¡Gracias por usar 1N4! Estoy feliz de ser de servicio.
A continuación se muestra una lista de todos los comandos que están disponsibles para usted. Si encuentra algún problema, por favor informalo a través de nuestro [rastreador de problemas](https://github.com/ArchitecturalDogSoftware/1N4/issues).\
"""
help-footer = """\
Propiedad de Arden Inc., versión %V+neon.
Número de Modelo. '4D3431442D554E4954' cor. 2.\
"""

help-global = "Comandos globales"
help-guild = "Comandos del servidor"
help-missing = "No se han encontrado comandos."

help-tag-subcommands = "Tiene subcomandos"
help-tag-dms = "Utilizable en mensajes directos"
help-tag-nsfw = "NSFW"

help-button-action-reply = "Este botón creará una respuesta a este mensaje."
help-button-action-url = "Este botón abrirá una página en su navegador predeterminado."

help-button-open = "Abrirlo"
help-button-view = "Verlo/a"

help-button-label-build-information = "Información de compilación"
help-button-label-source-code = "Código fuente"
help-button-label-licenses = "Licencias"
help-button-label-privacy-policy = "Directiva de privacidad"
help-button-label-security-policy = "Directiva de seguridad"

help-build-information-header = "Información de compilación"

localizer-reloaded = "¡Actualizado!"
localizer-locales = "Configuraciones regionales"
localizer-unknown = "Configuración regional desconocida"

ping-start = "Calculando..."
ping-finish = "Operación exitosa!"

poll-create-title = "Crear una encuesta nueva"
poll-invalid-url = "URL no válida"

role-load-failed = "No se pudo cargar a lista de selectores de roles."
role-load-missing = "No ha agregado ningún selector de roles."

role-added = "Se ha añadido el rol."
role-removed = "Se ha eliminado el rol."

role-invalid-icon = "El icono de rol debe ser un emoticono."
role-selector-added = "Se ha añadido un selector de roles."
role-selector-duplicate = "El rol dado ya se ha añadido."
role-selector-limit = "Se ha alcanzado el número máximo de selectores."

role-remove-emptied = "Se han eliminado todos los selectores de roles."
role-remove-missing = "El rol seleccionado ya se ha eliminado."

role-finished = "Finalizados los selectores de roles."

[ui-input]
poll-create-title = "Titulo"
poll-create-image = "URL de la imagen"
poll-create-description = "Texto del cuerpo"
